import { Metadata } from "next";

export const metadata: Metadata = {
  title: "StahlForce - About Us",
  description: "Generated by create next app",
};

export default function AboutUsPage() {
  return (
    <div className="bg-white">
      <main className="">
        About Us
      </main>
    </div>
  );
}
