import { Metadata } from "next";
import QualificationsCert from "../../../component/HomeComponent/QualificationsCert";

export const metadata: Metadata = {
    title: "StahlForce - Qualifications and Certifications",
    description: "Generated by create next app",
};

export default function QualificationsCerts() {
    return (
        <div>
            <main>
                <QualificationsCert />
            </main>
        </div>
    );
}