import { Metadata } from "next";
import QuickInquiry from "../../../component/HomeComponent/QuickInquiry";

export const metadata: Metadata = {
    title: "StahlForce - Contact Us",
    description: "Generated by create next app",
};

export default function Contact() {
    return (
        <div>
            <main>
                <QuickInquiry/>
            </main>
        </div>
    );
}