import { Metadata } from "next";
import PrecisionProduct from "../../../component/HomeComponent/PrecisionProduct";

export const metadata: Metadata = {
    title: "StahlForce - Qualifications and Certifications",
    description: "Generated by create next app",
};

export default function PrecisionProducts() {
    return (
        <div>
            <main>
                <PrecisionProduct />
            </main>
        </div>
    );
}