import { Metadata } from "next";
import SliderHome from "../../component/HomeComponent/SliderHome";
import ProductSeries from "../../component/HomeComponent/ProductSeries";
import CoreTechnical from "../../component/HomeComponent/CoreTechnical";
import QuickParameter from "../../component/HomeComponent/QuickParameter";

export const metadata: Metadata = {
  title: "StahlForce - Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="">
      <main className="">
        <SliderHome />
        <div id="core-technical">
          <CoreTechnical />
        </div>
        <div id="products">
          <ProductSeries />
        </div>
        <div id="parameters">
          <QuickParameter />
        </div>
      </main>
    </div>
  );
}
